#!/bin/bash

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension

# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
jupyter trust clustering/dbscan.ipynb
jupyter trust clustering/kmeans.ipynb
jupyter trust clustering/lloyd_kmeans_demo.ipynb
jupyter trust graph_centrality/centrality.ipynb
